# Generated by Django 4.1.1 on 2023-08-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='name',
            new_name='phone',
        ),
    ]
